<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="1" total="6" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-03-21T19:46:58 IST" name="Suite" finished-at="2024-03-21T19:47:20 IST" duration-ms="22321">
    <groups>
      <group name="Smoke">
        <method signature="SubmitOrder.SignOut()[pri:0, instance:Selenium.SubmitOrder@23941fb4]" name="SignOut" class="Selenium.SubmitOrder"/>
      </group> <!-- Smoke -->
    </groups>
    <test started-at="2024-03-21T19:46:58 IST" name="Error Validation Test" finished-at="2024-03-21T19:47:10 IST" duration-ms="12301">
      <class name="Selenium.ErrorValidationsTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Selenium.ErrorValidationsTest@747f281]" started-at="2024-03-21T19:46:58 IST" name="launchApplication" finished-at="2024-03-21T19:47:05 IST" duration-ms="7108" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method retried="true" signature="failedTest()[pri:0, instance:Selenium.ErrorValidationsTest@747f281]" started-at="2024-03-21T19:47:05 IST" name="failedTest" finished-at="2024-03-21T19:47:06 IST" duration-ms="570" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect] but found []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect] but found []
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at Selenium.ErrorValidationsTest.failedTest(ErrorValidationsTest.java:11)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failedTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Selenium.ErrorValidationsTest@747f281]" started-at="2024-03-21T19:47:06 IST" name="tearDown" finished-at="2024-03-21T19:47:06 IST" duration-ms="343" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Selenium.ErrorValidationsTest@747f281]" started-at="2024-03-21T19:47:06 IST" name="launchApplication" finished-at="2024-03-21T19:47:09 IST" duration-ms="3025" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="failedTest()[pri:0, instance:Selenium.ErrorValidationsTest@747f281]" started-at="2024-03-21T19:47:09 IST" name="failedTest" finished-at="2024-03-21T19:47:10 IST" duration-ms="555" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect] but found []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect] but found []
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at Selenium.ErrorValidationsTest.failedTest(ErrorValidationsTest.java:11)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:249)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failedTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Selenium.ErrorValidationsTest@747f281]" started-at="2024-03-21T19:47:10 IST" name="tearDown" finished-at="2024-03-21T19:47:10 IST" duration-ms="373" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Selenium.ErrorValidationsTest -->
    </test> <!-- Error Validation Test -->
    <test started-at="2024-03-21T19:46:58 IST" name="Submit Order Test" finished-at="2024-03-21T19:47:20 IST" duration-ms="22321">
      <class name="Selenium.SubmitOrder">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Selenium.SubmitOrder@23941fb4]" started-at="2024-03-21T19:46:58 IST" name="launchApplication" finished-at="2024-03-21T19:47:04 IST" duration-ms="6134" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="SubmitOrderTest()[pri:0, instance:Selenium.SubmitOrder@23941fb4]" started-at="2024-03-21T19:47:04 IST" name="SubmitOrderTest" finished-at="2024-03-21T19:47:10 IST" duration-ms="6018" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SubmitOrderTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Selenium.SubmitOrder@23941fb4]" started-at="2024-03-21T19:47:10 IST" name="tearDown" finished-at="2024-03-21T19:47:11 IST" duration-ms="430" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Selenium.SubmitOrder@23941fb4]" started-at="2024-03-21T19:47:11 IST" name="launchApplication" finished-at="2024-03-21T19:47:14 IST" duration-ms="3741" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="SignOut()[pri:0, instance:Selenium.SubmitOrder@23941fb4]" started-at="2024-03-21T19:47:14 IST" name="SignOut" finished-at="2024-03-21T19:47:16 IST" duration-ms="1300" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SignOut -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Selenium.SubmitOrder@23941fb4]" started-at="2024-03-21T19:47:16 IST" name="tearDown" finished-at="2024-03-21T19:47:16 IST" duration-ms="364" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Selenium.SubmitOrder@23941fb4]" started-at="2024-03-21T19:47:16 IST" name="launchApplication" finished-at="2024-03-21T19:47:19 IST" duration-ms="2481" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="OrderHistory()[pri:0, instance:Selenium.SubmitOrder@23941fb4]" started-at="2024-03-21T19:47:19 IST" name="OrderHistory" finished-at="2024-03-21T19:47:20 IST" depends-on-methods="Selenium.SubmitOrder.SubmitOrderTest" duration-ms="1495" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OrderHistory -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Selenium.SubmitOrder@23941fb4]" started-at="2024-03-21T19:47:20 IST" name="tearDown" finished-at="2024-03-21T19:47:20 IST" duration-ms="307" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Selenium.SubmitOrder -->
    </test> <!-- Submit Order Test -->
  </suite> <!-- Suite -->
</testng-results>
